config/routes.rb
Rails.application.routes.draw do
  root 'statics#home'

  get 'playlist/subscribe/:id', to: "playlists#subscribe", as: "subscribe_playlist"
  get 'playlist/unsubscribe/:id', to: "playlists#unsubscribe", as: "unsubscribe_playlist"
  get 'playlist/remove/:id', to: "playlists#remove", as: "remove_playlist"
  get 'playlists/show_all', to: "statics#show_all", as: "playlists_show_all"

  resources :videos
  resources :playlists
  devise_for :users


  get 'users/:id' => "users#show", as: "users_show"

  get 'playlist/:playlist_id/videos/new' => "videos#new", as: "videos_new"
  get 'playlists/:playlist_id/video/:id/edit' => "videos#edit", as: "videos_edit"
  get 'playlist/:playlist_id/videos/show' => "videos#show", as: "videos_show"



end

app/models/playlist.rb
class Playlist < ActiveRecord::Base

  has_and_belongs_to_many :users
  belongs_to :owner, :class_name => "User", :foreign_key => "user_id"

  has_many :videos
end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, styles: {thumb: '100x100>', square: '200x200#', medium: '300x300>'}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  # has_attached_file :picture, :styles => { :thumb => "200x200#" }
  has_and_belongs_to_many :playlists
  has_many :owned, :class_name => "Playlist"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base

  belongs_to :playlist
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :profile_picture, :email, :password, :password_confirmation, :avatar])

     devise_parameter_sanitizer.permit(:account_update, keys: [:username, :profile_picture, :email, :password, :password_confirmation, :avatar])
   end

   def after_sign_in_path_for(resource)
     users_show_path(current_user)
   end

  protect_from_forgery with: :exception
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def subscribe
      playlist = Playlist.find(params[:id])
      current_user.playlists.push(playlist)
      redirect_to "/playlists"
  end

  def unsubscribe
      playlist = Playlist.find(params[:id])
      current_user.playlists.destroy(playlist)
      redirect_to "/playlists"
  end

  def remove

    playlist = Playlist.find(params[:id])
    current_user.playlists.destroy(playlist)
    redirect_to "/users/#{current_user.id}"

  end

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
    
    @list_id = Playlist.ids
    @randlist = @list_id.sample

    # id = @playlists.each do |playlist|
    #   playlist.id
    # end
    # @randlist = @playlist.sample
    # puts @randlist

    render layout: "not_form_layout"
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    playlist = Playlist.find(params[:id])
    @videos = playlist.videos
    render layout: "not_form_layout"
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
    playlist = Playlist.find(params[:id])
    @videos = playlist.videos
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.owner = current_user

    respond_to do |format|
      if @playlist.save
        id = @playlist.id.to_s
        format.html { redirect_to '/playlist/'+id+'/videos/new' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update

    # @playlist = Playlist.find(params[:id])
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to "/users/#{current_user.id}", notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:title, :genre, :length)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
    render layout: "home_layout"
  end

  def show_all
    
    @playlists = Playlist.all
    render layout: "not_form_layout"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @playlists = @user.playlists
    @owned_playlists = @user.owned
    render layout: "not_form_layout"
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /videos
  # GET /videos.json
  def index
    playlist = params[:playlist_id]
    @videos = playlist.videos
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @playlist_id = params[:playlist_id]
  end

  # GET /videos/new
  def new
    @video = Video.new
    @playlist_id = params[:playlist_id]
    @videos_array = []
  end

  # GET /videos/1/edit
  def edit
    @playlist_id = params[:playlist_id]
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @videos = params[:videos]
    id = @video.playlist.id.to_s

    if @videos != 0 
      respond_to do |format|
        if @video.save
          format.html {redirect_to '/playlist/'+id+'/videos/new', notice: 'Video was successfully created. Add another?' }
          format.json { render :show, status: :created, location: @video }
        else
          format.html { render :new }
          format.json { render json: @video.errors, status: :unprocessable_entity }
        end
      end
    else
      format.html { render :new }
      format.json { render json: @video.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    id = @video.playlist.id.to_s
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to '/playlists/'+id+'/edit', notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :genre, :artist, :playlist_id, :start_time, :end_time, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Danceoke</title>
  <link href='https://fonts.googleapis.com/css?family=Antic+Slab' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'application', 'https://www.youtube.com/iframe_api' %>
  <%= csrf_meta_tags %>

</head>
<body class="form_background">


<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">DANCEOKE</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right ">
          <% if current_user %>
            <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
            <li><a href="/users/<%= current_user.id %>"><%= current_user.username %></a></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>
  
</body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Danceoke</title>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans|Indie+Flower|Arimo|Antic+Slab' rel='stylesheet' type='text/css'>  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>
<body class="home_background">



<%= yield %>


</body>
</html>

app/views/layouts/not_form_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Danceoke</title>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans|Indie+Flower|Arimo|Antic+Slab' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'application', 'https://www.youtube.com/iframe_api' %>
  <%= csrf_meta_tags %>

</head>
<body class="not_form_background">

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">DANCEOKE</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
            <li><a href="/users/<%= current_user.id %>"><%= current_user.username %></a></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <hr>
  <div class="container">
    <%= yield %>
  </div>
  
</body>
</html>

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group"> 
      <%= f.label :title %><br>
      <%= f.text_field :title, :class => 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :genre %><br>
    <%= f.text_field :genre, :class => 'form-control' %>
  </div>

  <div class="actions btn btn-default">
    <%= f.submit %>
  </div><br/><br/>

<% end %>

app/views/playlists/edit.html.erb
<div class="all_forms">
  <div class="form-inner">

    <h1>Edit <%= @playlist.title %></h1>

    <ul>
      <% @videos.each do |video| %>

        <li><h4><a class="btn btn-default" href="/playlists/<%= @playlist.id %>/video/<%= video.id %>/edit"> Edit</a> <%= video.title %></h4></li><br/>

      <% end %>
    </ul>

    <div class="btn btn-default"><a href= '/playlist/<%= @playlist.id %>/videos/new'>New Video</a></div><br/><br/>

    <%= render 'form' %>


    <%= link_to 'Cancel', playlist_path, :class => "btn btn-default" %>
    


  </div>
</div>

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Playlists</h1>
          

    <div class="col-md-12 user_header">
    <div class="col-md-6 user_header">
          <a href="/playlists" class="btn user_link show_all">
            <i class="fa fa-list" aria-hidden="true"> ALL</i>
          </a>
          <a href=<%= new_playlist_path %> class="btn user_link show_new">
            <i class="fa fa-plus-square" aria-hidden="true"> NEW</i> 
          </a>
          <a href="/users/<%= current_user.id %>" class="btn user_link show_all">
            <i class="fa fa-list" aria-hidden="true"> My Lists</i>
          </a>
    </div>
    </div>

    <br/>

    <div class="col-lg-12 random">
    <div class="random btn btn-default"><a class="randomize" href="/playlists/<%= @randlist %>">Random</a></div>
    </div>
    <br/>

    <% @playlists.each do |playlist| %>
      <div class="col-lg-4 col-md-6 col-xs-12 portfolio-item">
          <a class="thumbnail" href="/playlists/<%= playlist.id %>">
              <br/>
              <img class="img-responsive" src="http://img.youtube.com/vi/<%= playlist.videos[0].url%>/0.jpg" alt="<%= playlist.title %>" >
          </a>
          <div class="subscribe playlist_title"><strong><h2><%= link_to playlist.title, playlist %></h2></strong></div>
          <% if playlist.user_id.to_i != current_user.id.to_i %>
            <% unless current_user.playlists.exists?(playlist) %>
              <div class="subscribe"><%= link_to 'Subscribe', subscribe_playlist_path(playlist.id) %></div><br/><br/>
            <% else %>
              <div class="subscribe"><%= link_to 'Unsubscribe', unsubscribe_playlist_path(playlist.id) %></div><br/><br/>
            <% end %>
          <% end %>
              </div>
      <% end %>            
  </div>
</div>

app/views/playlists/new.html.erb
<div class="all_forms">
  <div class="form-inner">
    <h1>New Playlist</h1>

    <%= render 'form' %>


    <div class="btn btn-default"><%= link_to 'Cancel', playlists_path %></div>

  </div>
</div>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= @playlist.title %></h1>
  </div>
</div>


<div class="row">
  <div>
  <div class="video_box col-md-8 col-xs-12">
      <div id="youtubePlayer" class="col-xs-12"></div><br/>
      <div class="player_controllers">
        <i href="#" id="restart" class="fa fa-refresh fa-2x" aria-hidden="true" title="Restart"></i>
      </div>
  </div>
</div>

  <div class="col-md-4 info_box">
    <h3>Genre</h3>
      <p class="video_title"><%= @playlist.genre %></p><br/>
    <h3>Videos</h3>
    <ul>
      <% @videos.each do |video| %>
        <div class="video_title">
          <h4><%= video.title %></h4><br/>
          <h5><%= video.artist %></h5> 
        </div>
      <% end %>
    </ul>
  </div>
  <br/>

  <div class="col-lg-4 links_box">
      <a href=<%= playlists_path %> class="btn user_link">
        <i class="fa fa-list" aria-hidden="true"> ALL</i>
      </a>
      <a href=<%= new_playlist_path %> class="btn user_link">
        <i class="fa fa-plus-square" aria-hidden="true"> NEW</i> 
      </a>
      <a href=<%= users_show_path %> class="btn user_link">
        <i class="fa fa-user aria-hidden="true"> HOME</i> 
      </a>
  </div>

  
  <div class="col-lg-4 bottom_box">
    <% if @playlist.user_id.to_i == current_user.id.to_i %>
        <%= link_to 'Edit', edit_playlist_path(@playlist), :class => "video_title" %><br/>
        <%= link_to 'Delete', @playlist, method: :delete, data: { confirm: 'Are you sure?' }, :class => "video_title" %>
      <% else %>
        <%= link_to 'Unsubscribe', remove_playlist_path(@playlist.id), :class => "video_title" %>
    <% end %>
  </div>

  <input id="youtubeVideosList" type="hidden" value='[
  <% @playlist.videos.each do |video| %>
    {"videoId": "<%= video.url %>", "startSeconds": <%= video.start_time %>, "endSeconds": <%= video.end_time %>}
    <% if video != @playlist.videos.last then %>, <% end %>
  <% end %>
  ]' />

app/views/statics/home.html.erb
<div class="hide_button_container">
  <div id="dance_button"><span>DANCEOKE</span></div>
</div>

<div class="home_links" id="hideshow" value='hide/show'>
    <% if current_user %>
      <a class="side_links" href="/users/<%= current_user.id %>"><%= current_user.username %></a>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, :class => 'side_links' %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path, :class => 'side_links' %>
      <%= link_to "Register", new_user_registration_path, :class => 'side_links' %>
      <%= link_to "Videos", playlists_show_all_path, :class => 'side_links' %>
    <% end %>
</div>

app/views/statics/show_all.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Playlists</h1>
    </div>


    <% @playlists.each do |playlist| %>
      <div class="col-lg-4 col-md-6 col-xs-12 portfolio-item">
          <a class="thumbnail" href="/playlists/<%= playlist.id %>">
              <img class="img-responsive" src="http://img.youtube.com/vi/<%= playlist.videos[0].url%>/0.jpg" alt="<%= playlist.title %>">
          </a>
          <div class="subscribe playlist_title"><strong><%= link_to playlist.title, playlist %></strong></div><br/>
      </div>
      <% end %>            
  </div>
</div>

app/views/users/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="page-header"><%= @user.username %></h1>  
      </div>

      <div class="col-md-12 user_header">
      <div class="col-md-6 user_header">
        <h2>Playlists</h2> 
      </div>
      <div class="col-md-6 user_header_2">
            <a href="/playlists" class="btn user_link show_all">
              <i class="fa fa-list" aria-hidden="true"> ALL</i>
            </a>
            <a href=<%= new_playlist_path %> class="btn user_link show_new">
              <i class="fa fa-plus-square" aria-hidden="true"> NEW</i> 
            </a>
      </div>
      </div>
          
      </div>

      <br/>

    <div class="col-md-12">
       
        <% @playlists.each do |playlist| %>
        <h2><a href="/playlists/<%= playlist.id %>"><%= playlist.title %></a></h2>
          <h3><p class="lead"><%= playlist.genre %></p></h3>
          <a class="thumbnail list_playlists" href="/playlists/<%= playlist.id %>">
            <img class="img-responsive" src="http://img.youtube.com/vi/<%= playlist.videos[0].url%>/hqdefault.jpg" alt="<%= playlist.title %>" >
          </a>
        <hr>
        <% end %>

        <% @owned_playlists.each do |playlist| %>
        <h2><a href="/playlists/<%= playlist.id %>"><%= playlist.title %></a></h2>
          <h3><p class="lead"><%= playlist.genre %> </p></h3>
          <a class="thumbnail list_playlists" href="/playlists/<%= playlist.id %>">
            <img class="img-responsive" src="http://img.youtube.com/vi/<%= playlist.videos[0].url%>/hqdefault.jpg" alt="<%= playlist.title %>" >
          </a>
        <hr>
        <% end %>
    </div>
              
    </div>

    <hr>

  </div>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-sm-12">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => 'form-control' %>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :url %><br>
    <%= f.text_field :url, :class => 'form-control' %>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :genre %><br>
    <%= f.text_field :genre, :class => 'form-control' %>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :artist %><br>
    <%= f.text_field :artist, :class => 'form-control' %>
  </div>

  <div class="form-group col-sm-12">
    <%= f.label :start_time %><br>
    <%= f.number_field :start_time, :class => 'form-control' %>
  </div>

  <div class="form-group col-sm-12">
    <%= f.label :end_time %><br>
    <%= f.number_field :end_time, :class => 'form-control' %>
  </div>

  <div class="form-group col-sm-12">
    <%= f.hidden_field :playlist_id, :value => @playlist_id %>
  </div>
  <div class="actions btn btn-default">
    <%= f.submit %>
  </div><br/><br/>
  
<% end %>

app/views/videos/edit.html.erb
<div class="all_forms">
  <div class="form-inner">

    <h1>Edit <strong><%= @video.title %></strong></h1>

    <%= render 'form' %>

    <%= link_to 'Show', @video, :class => "btn btn-default" %>
    <%= link_to 'Back to Playlist', playlist_path, :class => "btn btn-default" %>

  </div>
</div>

app/views/videos/new.html.erb
<div class="all_forms">
  <div class="form-inner">

    <h1>New Video</h1>

    <%= render 'form' %>

    <div class="btn btn-default"><a href="/users/<%= current_user.id %>">All Playlists</a></div>
    <div class="btn btn-default"><a href="/playlists/<%= @playlist_id %>/edit">Playlist</a></div>


  </div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<a href="/users/<%= current_user.id %>">My Playlists</a>


<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<iframe width="560" height="315" src="http://www.youtube.com/v/VUxh-jw-C-w?version=3&enablejsapi=1" frameborder="0" allowfullscreen></iframe>

<p>
  <strong>Genre:</strong>
  <%= @video.genre %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @video.artist %>
</p>

<p>
  <strong>Playlist:</strong>
  <%= @video.playlist.title %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>